apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mcp
  namespace: rhalexandrini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mcp
  template:
    metadata:
      labels:
        app: k8s-mcp
    spec:
      serviceAccountName: k8s-mcp
      containers:
        - name: k8s-mcp
          image: rhalexandrini/k8s-mcp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MCP_TRANSPORT
              value: "streamable_http"
            - name: MCP_PORT
              value: "8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
